package colourspace

import "core:math"


_ :: math

when ENABLE_HDR {
	// Products of XYZ <-> Rec. 2020 and XYZ <-> LMS matrices.
	// GENERATED BY THE BUILDER TOOL; DO NOT EDIT BY HAND.

	_LINEAR_LMS_TO_LINEAR_REC_2020 :: #row_major matrix[3, 3]f32{
		2.1401402950, -1.2463558912, 0.1064317226,
		-0.8848324418, 2.1631727219, -0.2783615887,
		-0.0485790595, -0.4544909000, 1.5023562908,
	}

	_LINEAR_REC_2020_TO_LINEAR_LMS :: #row_major matrix[3, 3]f32{
		0.6166884303, 0.3601590693, 0.0230432935,
		0.2651402056, 0.6358565092, 0.0990302339,
		0.1001506448, 0.2040043175, 0.6963247061,
	}


	@(require_results) rec_2020_to_oklab :: #force_inline proc "contextless" (rec_2020: Linear_Rec_2020) -> OkLab {
		// Convert OkLab to Linear LMS (cone response space).
		lms: _Linear_LMS = (_LINEAR_REC_2020_TO_LINEAR_LMS * rec_2020)

		// Cube root applies the nonlinear compression of OkLab to LMS, mimicking
		// human perceptual response, before mixing into a/b/L axes.
		return (_LINEAR_LMS_TO_OKLAB * OkLab{
			math.cbrt(lms.x),
			math.cbrt(lms.y),
			math.cbrt(lms.z),
		})
	}

	@(require_results) oklab_to_rec_2020 :: #force_inline proc "contextless" (lab: OkLab) -> Linear_Rec_2020 {
		// Convert OkLab to Linear LMS (cone response space).
		lms: _Linear_LMS = (_OKLAB_TO_LINEAR_LMS * lab)

		// Cube reverses the nonlinear compression of OkLab from LMS, undoing
		// the perceptual mimicry, before mixing into Linear Rec. 2020.
		return (_LINEAR_LMS_TO_LINEAR_REC_2020 * Linear_Rec_2020{
			lms.x * lms.x * lms.x,
			lms.y * lms.y * lms.y,
			lms.z * lms.z * lms.z,
		})
	}


	@(require_results) rec_2020_to_oklch :: #force_inline proc "contextless" (rec_2020: Linear_Rec_2020) -> OkLch {
		return oklab_to_oklch(rec_2020_to_oklab(rec_2020))
	}

	@(require_results) oklch_to_rec_2020 :: #force_inline proc "contextless" (lch: OkLch) -> Linear_Rec_2020 {
		return oklab_to_rec_2020(oklch_to_oklab(lch))
	}
}
